### PR TITLE
Fail fast on missing bindings before running GuiceBerryEnvMain.

### PR DESCRIPTION
**Pull request by kleerwater**
It's painful to start servers only to find that there is an unsatisfied binding in the test

### CODE REVIEW

**Comment by zorzella** [comment]
I'm going to accept the pull request, though I'll tweak the new test a bit to give better error messages.

Thanks for the contribution. Sorry for the delay in the review.

**Comment by zorzella** [comment]
FYI here are the polishes:

https://github.com/zorzella/guiceberry/commit/aee23d55bb5b3a17ced1a0fe67e48c3f0c25a40f

**Comment by kleerwater** [comment]
Thanks for reviewing and pulling it.

**Comment by zorzella** [comment]
Note: while trying to deploy the new GuiceBerry release into our larger codebase I encountered an issue with this change that I did not anticipate. I still plan on keeping this change (unless I find it intractable to fix all issues caused by it), but here's an amended portion of the release notes to cover that: 

* GuiceBerry to fail fast if there are missing bindings. With this change,
  GuiceBerry will make sure the test class is injectable (i.e. there are no
  missing bindings, transitively) before it runs its GuiceBerryEnvMain. This
  should make missing bindings fail the test faster, thus speeding up the
  development/fix cycle. This does change the order of events in a subtle way,
  though -- e.g. if GuiceBerryEnvMain was used to change some global static
  state that is then read by a singleton binding, this will stop working
  properly, as that singleton will be built before GuiceBerryEnvMain runs.

**Comment by zorzella** [comment]
Ok, as discussed offline, the problem was actually just with things used by the TestWrapper, not as broad as I originally thought. It also is fixable, and I did just that:

https://github.com/zorzella/guiceberry/commit/882ffd43e7fc400c8ef72e17878bbacdaf49bf55

**Pull request merged**
